"""User va Organizer model bir birga relationship boldi, one-to-one boldi

Revision ID: 6ccbe85755a7
Revises: 758649e9b2f2
Create Date: 2026-08-15 17:00:17.668741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ccbe85755a7'
down_revision: Union[str, Sequence[str], None] = '758649e9b2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_organizers_user_id'), 'organizers', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_organizers_user_id'), 'organizers', type_='unique')
    # ### end Alembic commands ###
