"""Organizer jadval yaratildi

Revision ID: 758649e9b2f2
Revises: 1aa7f534367f
Create Date: 2026-08-14 21:18:38.086967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '758649e9b2f2'
down_revision: Union[str, Sequence[str], None] = '1aa7f534367f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizers',
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='organizerstatus'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.String(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.String(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_organizers_approved_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organizers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizers'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizers')
    # ### end Alembic commands ###
